### ISSUE TITLE
[Windows][26.908.3777.0] Primary renderer crashes on startup with `r is not a function`; rollback to 26.903.9818.0 fixes it

### ISSUE THREAD

**Issue by kiyo275** [openai/codex#44748]
### What version of the Codex App are you using?

26.908.3777.0

Previous working version: 26.903.9818.0

### Platform

Windows 11 Pro x64

### Issue

Immediately after updating Codex Desktop from 26.903.9818.0 to 26.908.3777.0, the app became unusable on startup. The main window shows the generic **“ChatGPT has encountered a problem”** error screen every time.

This is not isolated to the Pet/avatar overlay. The **primary renderer** itself crashes.

Relevant log sequence:

```text
[AppServerConnection] ... next=connected ... initialized=true
[electron-message-handler] Initial route prefetch failed; rendering will retry errorMessage="r is not a function" errorName=Error errorStack="Error: r is not a function" rendererWindowAppearance=primary route=primary windowType=electron
[chatgpt-account-lookup] ... authenticatedAccountPresent=true authMethod=chatgpt ... result=succeeded
[electron-message-handler] error boundary ... errorMessage="r is not a function" errorName=Error errorStack="Error: r is not a function" name=AppRoutes rendererWindowAppearance=primary rendererWindowVisible=true
```

So the local app-server connects successfully and ChatGPT authentication succeeds, then the React/Electron primary route enters an error boundary.

### Reproduction

1. Start from working Codex Desktop 26.903.9818.0 on Windows 11.
2. Update to 26.908.3777.0.
3. Launch Codex.
4. Main window consistently shows the generic “ChatGPT has encountered a problem” screen.

Reproduction frequency: 100% on this machine.

### Troubleshooting already performed

The following did **not** fix the issue:

- Fully terminated all `ChatGPT.exe` processes and restarted.
- Windows Settings → App → Repair.
- Repair verified 5,511 package files and re-registered the package successfully.
- Removed/recreated renderer caches (`Cache`, `Code Cache`, `GPUCache`, Dawn caches, Shader caches, etc.).
- Moved the entire Codex web profile aside and launched with a fresh profile.

The crash remained identical.

Windows AppXDeploymentServer logs confirm the update path:

```text
OpenAI.Codex_26.903.9818.0_x64__2p2nqsd0c76g0
is updating to
OpenAI.Codex_26.908.3777.0_x64__2p2nqsd0c76g0
```

### Strong regression confirmation

I rolled back the exact app package from 26.908.3777.0 to 26.903.9818.0 using a valid Microsoft Marketplace-signed MSIX and:

```powershell
Add-AppxPackage -Path <26.903.9818.0.msix> -ForceUpdateFromAnyVersion -ForceApplicationShutdown
```

After rollback:

```text
Version : 26.903.9818.0
Status  : Ok
```

Codex launched normally again immediately, with the same user data and Windows environment.

This strongly suggests a regression introduced in 26.908.3777.0 rather than local cache/profile corruption.

### Related issue

Possibly related to #44739, which reports the same `r is not a function` / `AppRoutes` error on 26.908.3777.0 in the `avatarOverlay` renderer. In this case, however, `rendererWindowAppearance=primary`, so the entire app startup UI is affected.

### Additional log noise observed

A later warning also appears:

```text
plugin `sites` was not found in marketplace `openai-bundled`
```

However, this happens after the primary renderer has already failed, so it does not appear to be the initiating failure.

**Comment by MarekMazurek** [comment]
Additional confirmation from another Windows 11 x64 machine (OS build 26200), diagnosed on 2026-09-11.

**Affected versions**
- Store package: `OpenAI.Codex` **26.908.3777.0**
- Internal app version: **26.908.31457**, build **8690**

**Observed failure**
Two launches with the existing user profile produced the same primary-window error after the local app-server had connected successfully:

```text
[AppServerConnection] hostId=local initialized=true next=connected
[electron-message-handler] error boundary
errorMessage="r is not a function"
errorName=Error
name=AppRoutes
rendererWindowAppearance=primary
rendererWindowVisible=true
```

The component stack begins with `Lazy` and references `app-initial-5efcb2fc7e21.js:8057:59005`.

**Isolation and integrity checks**
- A separate `CODEX_HOME`, retaining sign-in only, plus fresh Electron/Chromium user data also produced `r is not a function` in the `AppRoutes` boundary. In that isolated run, the recorded failing window was `avatarOverlay`.
- The installed package reported `Status: Ok`.
- The SHA-256 of the affected `app-initial-5efcb2fc7e21.js` file matched its embedded ASAR integrity hash. This was a check of that asset, not a verification of every package file.

**Previous-version comparison**
Unmodified application files from package **26.903.9818.0** (internal app version **26.903.71938**), with a valid OpenAI executable signature, were launched separately using the original user data. The local engine connected, thread read/list/resume requests succeeded, and no matching UI error appeared in the observed startup logs. The user data was preserved.

This was a separate recovery launch, not a successful downgrade of the Store registration; Windows rejected registering the copied package manifest outside the package root. It is a temporary workaround, not a complete regression test of the older version.

**Additional updater symptom**
The affected version also logged a Windows Store update-check JSON parsing error: `Unexpected token '\b' ... is not valid JSON`. A direct HTTPS request to the app's configured update manifest returned valid JSON, and the Store reported no newer update. This is reported as a separate observation, not as the cause of the frontend exception.

Please include both the primary startup route and avatar overlay in validation of the fix.

**Comment by danialbka** [comment]
﻿Additional Windows report, with a tentative recovery workaround, prepared with Codex assistance from local diagnostics.

**Affected installation**
- Windows x64, MSIX package `OpenAI.Codex_26.908.4561.0_x64__2p2nqsd0c76g0`
- Internal app version in `owl-app.ini`: `26.908.40401`
- Main window stuck on **“ChatGPT hit a snag.”**

**Observed log fields** (selected excerpts, unrelated fields omitted):
```text
Initial route prefetch failed; rendering will retry
errorMessage="r is not a function" route=primary windowType=electron

[chatgpt-account-lookup] authenticatedAccountPresent=true authMethod=chatgpt result=succeeded

error boundary errorMessage="r is not a function" name=AppRoutes rendererWindowAppearance=primary
```
The component stack referenced `app://-/assets/app-initial-7b019c5eda5f.js`.

**Recovery attempts and outcome**
1. Closed all `ChatGPT.exe` processes, renamed `Cache`, `Code Cache`, `GPUCache`, `DawnGraphiteCache`, and `DawnWebGPUCache` to timestamped backup names, and relaunched. The user confirmed the snag persisted; subsequent logs confirmed the same error.
2. Closed the app again and renamed only `Local Storage` and `Session Storage` to timestamped backup names under:
   `%LOCALAPPDATA%\Packages\OpenAI.Codex_2p2nqsd0c76g0\LocalCache\Roaming\Codex`
3. Relaunched the registered app. The user subsequently confirmed it was working.

**Limits of this observation:** an early post-relaunch log check still contained `r is not a function`, before the user reported recovery. We did not run repeated clean-start tests or identify a specific bad storage entry. This is therefore a user-confirmed recovery after these steps, not proof that resetting storage fixes the underlying bug or that corrupt storage caused it. It may be temporary or related to startup timing, consistent with the related investigation in #44720.

No application bundle patch, reinstall, rollback, or change to `.codex-global-state.json` was performed. Sign-in data and chat files were left in place, and the renamed storage directories were retained as backups. Resetting these interface stores can reset local UI state; the steps above describe this one recovery attempt, not a universal recommendation.

**Comment by andrewcdobbins** [comment]
Additional independent reproduction on Windows.

**Environment**

- Windows 11 Pro x64
- Microsoft Surface Pro 9
- Store package: `OpenAI.Codex 26.908.4561.0`
- `Get-AppxPackage` reports package `Status: Ok`

**Observed behaviour**

The ChatGPT Windows app updated to `26.908.4561.0` today, 11 September 2026. Immediately after the update, the application became unusable at startup.

Every attempted launch currently reaches:

> ChatGPT hit a snag  
> Something went wrong. Try again to continue.

This is the same visible failure described in this issue and in the existing `26.908.4561.0` report.

The application was working before the update. No Repair, Reset, reinstall, cache deletion or profile changes have been attempted, so the installation and local state have deliberately been left untouched pending a product fix or further diagnostics.

Package verification:

```powershell
Get-AppxPackage OpenAI.Codex | Select-Object Name, Version, Status, InstallLocation
```

returns:

```text
Name         Version       Status
OpenAI.Codex 26.908.4561.0 Ok
```

I can provide targeted logs from the affected installation if useful.
