### ISSUE TITLE
Computer Use compatibility issue

### ISSUE THREAD

**Issue by maguiremark228-byte** [openai/codex#32310]
### What version of the Codex App are you using (From “About Codex” dialog)?

ChatGPT 26.707.41301

### What subscription do you have?

computer-use兼容性问题 Codex Computer Use 1.0.1000366

### What platform is your computer?

macOS 15.7.7

### What issue are you seeing?

Symbol not found: _swift_task_addPriorityEscalationHandler

### What steps can reproduce the bug?

Feedback ID: no-active-thread-019f4ef3-fb16-77a0-86f3-40ee1251fcd0

**Comment by RicadoGz** [comment]
Adding an independent reproduction because this is still broken on macOS 14 with the currently bundled build.

### Environment

- macOS 14.8.4 (23J319), Apple Silicon
- ChatGPT app 26.707.41301 (build 5103)
- Computer Use plugin 1.0.1000366
- Native helper 26.708.1000366 (build 1000366)
- The helper's `Info.plist` declares `LSMinimumSystemVersion = 14.4`

### Minimal reproduction

Running the helper directly, even with only `--help`, fails before the service can start:

```text
$ "$HOME/.codex/plugins/cache/openai-bundled/computer-use/1.0.1000366/Codex Computer Use.app/Contents/MacOS/SkyComputerUseService" --help

dyld: Symbol not found: _swift_task_addPriorityEscalationHandler
  Referenced from: .../SkyComputerUseService
  Expected in: /usr/lib/swift/libswift_Concurrency.dylib
```

The helper passes `codesign --verify --deep --strict`. The failure occurs during dynamic linking, before Screen Recording or Accessibility permissions can be relevant. The client subsequently reports the generic error `Sky Computer Use native pipe startup failed`.

This also appears to be a remaining regression after #32032 was closed as completed: the current helper still reproduces the same missing-symbol failure on macOS 14.8.4. For comparison, an older helper build (857) launches on this OS, although it cannot be used with the current client because the API versions do not match.

### Suggested fix

- Rebuild the native helper with the appropriate Swift concurrency availability/back-deployment fix (related upstream context: swiftlang/swift#88428), or bundle a compatible runtime.
- Ensure the binary's actual deployment requirements match the advertised `LSMinimumSystemVersion = 14.4`.
- Add launch smoke tests on supported macOS 14 and 15 versions.
- Surface a specific OS/runtime compatibility error instead of the generic native-pipe startup failure.

Happy to provide additional non-sensitive diagnostics if useful.
