### ISSUE TITLE
[macOS Desktop 26.820.60940] code-mode tasks omit send_message_to_thread while read tools remain

### ISSUE THREAD

**Issue by alexander-dreyzen** [openai/codex#40852]
### What version of the Codex App are you using?

- ChatGPT / Codex Desktop: `26.820.60940` (build `7119`)
- Bundled CLI: `codex-cli 0.150.0-alpha.8`
- Prior working CLI/session comparison: `0.149.0-alpha.4.1`

### What platform is your computer?

- macOS `26.5.2` (build `25F84`)
- Apple Silicon / `arm64`

### What issue are you seeing?

After the update to Desktop `26.820.60940` / CLI `0.150.0-alpha.8`, code-mode Codex tasks no longer receive the complete first-party thread-management tool family.

The read side remains available and works:

- `list_threads`
- `read_thread`
- `wait_threads`
- title/archive/pin helpers

But the effectful task tools are omitted from the callable tool catalog, including:

- `send_message_to_thread`
- `create_thread`
- `fork_thread`
- `handoff_thread`
- `automation_update`

The immediate blocker is `send_message_to_thread`. In two independently bootstrapped Codex tasks, including a worker and coordinator on the same physical host, the exact result was:

```text
typeof tools.codex_app__send_message_to_thread === "undefined"
TypeError: tools.codex_app__send_message_to_thread is not a function
```

The destination task was uniquely resolved through the correct `remote-ssh-discovered:<host>.local` projection. Exact destination readback proved that no message input was created, so this is a missing callable-tool problem rather than target discovery, host routing, or an uncertain delivery result.

A retained session from the same environment on CLI `0.149.0-alpha.4.1` successfully called:

```js
await tools.codex_app__send_message_to_thread({
  threadId,
  hostId,
  prompt,
});
```

The installed `26.820.60940` bundle still contains the `send_message_to_thread` tool definition, but the updated app code explicitly filters a sensitive-tool set containing `automation_update`, `create_thread`, `send_message_to_thread`, `fork_thread`, and `handoff_thread` from code-mode/deferred catalogs unless separately enabled. There is no user-authored `mcp_servers.codex_app` entry in `config.toml`.

This leaves app guidance and installed workflows referring to a native task-send capability that the model cannot call.

### What steps can reproduce the bug?

1. Run Codex Desktop `26.820.60940` with bundled CLI `0.150.0-alpha.8` on macOS.
2. Open a code-mode task with an authenticated ChatGPT account.
3. Ask the task to coordinate an existing Codex task.
4. Confirm `list_threads`, `read_thread`, and `wait_threads` are callable.
5. Resolve an exact existing destination using `remote-ssh-discovered:<host>.local`.
6. Attempt one user-authorized `send_message_to_thread`.
7. Observe that the tool is absent from the callable catalog / is not a function.
8. Repeat in another independently bootstrapped task; the same omission occurs.

### What is the expected behavior?

When a user explicitly requests inter-task communication, Codex Desktop should expose the same native app-owned `send_message_to_thread` capability that worked in `0.149`.

At minimum:

- the app instructions and callable tool catalog must agree;
- an explicitly user-authorized send should not require editing `config.toml`;
- the read and write halves of the thread-management family should not be silently split;
- if the capability is intentionally unavailable, the app should provide a clear structured diagnostic rather than leaving installed workflows to discover a missing function at runtime.

### Impact

This breaks established multi-task coordination that requires a visible, source-accounted native send, including discussion, convergence, and handoff workflows. Raw App Server calls or manual/fallback transports are not equivalent because they do not create the same source event and can violate exactly-once/no-resend guarantees.

Unaffected read-only and helper-backed operations continue to work, which makes the regression particularly confusing.

### Additional information

No `config.toml` change was made. The issue reproduces with the correct host projection and in two independent tasks.

Related but not duplicate:

- #29223 — broader reports of fresh sessions losing the thread-management surface
- #26907 — remote-started threads missing thread tools
- #40793 — same Desktop/CLI build exposes these tools on Windows but prompts on every call

This report is narrower: on macOS build `26.820.60940`, read/list/wait remain callable while `send_message_to_thread` and the other effectful task tools are omitted entirely.

**Comment by mokiYang** [comment]
I inspected the Desktop 26.820.60940 app bundle and found a client-side filtering path that appears to explain the exact read/write split.

The bundle defines a filter that removes:

- automation_update
- create_thread
- send_message_to_thread
- fork_thread
- handoff_thread

from both top-level dynamic tools and the codex_app namespace.

During thread-start parameter construction, this filter is applied when the source/current task host is not classified as local. The local-host path instead enables the app-owned codex_app tool names through configuration.

This would explain why read-only tools remain available while the five effectful tools disappear on a remote-SSH host projection. The relevant distinction appears to be the source task's host classification, not the destination thread's resolved host.

The public CLI repository also introduced per-surface MCP exposure controls in commit 51c9ed6 (#36781), which is present in the Desktop-bundled 0.150.0-alpha.8 but not in 0.144.6.

**Comment by genzorr** [comment]
### Update: build 7303 static audit + working rollback control

I inspected the current macOS ARM64 production release, Desktop `26.825.32147` / build `7303`. The bundle contains:

- bundled CLI/app-server: `0.150.0-alpha.12.2`
- `codex-code-mode-host`: `0.150.0-alpha.12.2`
- `codex-app-tools` plugin: `0.1.3`

Static inspection found the same relevant composition still present: the five effectful thread tools are removed from the nonlocal task-start catalog, legacy dynamic calls are rejected in favor of the `codex_app` MCP server, and the replacement MCP is provisioned only on the local-host path. A newer bundled CLI therefore does not by itself establish that the Remote SSH regression is fixed.

This is **not** a runtime reproduction on build 7303; no fresh local-plus-Remote-SSH success test was performed on that build.

As a live control, after rolling Desktop back to the previously working `26.818.61809` / build `7019`, a fresh local task successfully exposed `create_thread` and created a new user-owned task on a managed Remote SSH host. That isolates the recovery to the Desktop stack rather than the remote CLI or connection.

The migration should be atomic: legacy effectful tools should not be removed unless the replacement `codex_app` MCP server is already provisioned and callable for that task. A useful regression matrix would cover local vs. Remote SSH, fresh vs. retained tasks, and replacement-present vs. replacement-unavailable cases. Related broader report: #40865.

**Comment by scicolonevalentino** [comment]
guys I can't work anymore... how did I solve this? :( it's so frustrating!!!

**Comment by mattLummus** [comment]
+1 having the same issue

**Comment by hillarylinmd** [comment]
Reproduced on 2026-09-01 with ChatGPT/Codex Desktop 26.825.51511 (build 7377), macOS 26.4.1 on Apple silicon. The `codex` executable on the affected host reports version 0.151.0.

In a task attached to a Remote SSH project, the read/helper side remained callable and worked (`list_threads`, `read_thread`, `wait_threads`, title and archive operations), while the effectful thread tools including `create_thread` and `send_message_to_thread` were absent from the callable tool catalog.

A full quit and reopen of the Desktop app restored a previously wedged archive operation, but did not restore `create_thread` or `send_message_to_thread`. Retesting after relaunch produced the same missing-tool result. This confirms the regression persists on build 7377.

Private project path, host name, and thread identifiers are intentionally omitted.

**Comment by Samvibed** [comment]
Additional reproducible evidence from a Linux SSH remote host on the current stable helper:

Environment:

- Linux x86_64 SSH executor
- Active SSH app-server/helper reports `codex-cli 0.152.1` after updating the standalone helper and restarting the user service
- Fresh top-level user thread (`thread_source=user`), not a subagent

Observed in the fresh 0.152.1 rollout metadata:

- `dynamic_tool_count = 20`
- Read/helper tools remain available, including `list_threads`, `read_thread`, `wait_threads`, `open_in_codex`, title/archive, and sidebar-management tools
- The callable catalog omits `create_thread`, `fork_thread`, `handoff_thread`, and `send_message_to_thread`; `automation_update` is also absent
- User config has multi-agent support enabled and no per-tool disable for these first-party task-management tools

Historical comparison from the same remote host:

- Fresh top-level user threads on `0.149.0` recorded `dynamic_tool_count = 16`
- Those sessions contained all four of `create_thread`, `fork_thread`, `handoff_thread`, and `send_message_to_thread`, and the cross-thread workflow was usable

Updating/restarting the SSH app-server and then creating a new top-level thread did not restore the tools, so this is not the stale-helper mismatch described in #41759. The tools are already absent from the initial persisted dynamic-tool manifest, before the model can call them.

This appears to extend the reported behavior from macOS code-mode tasks to Linux SSH Remote tasks on 0.152.1. In the degraded state, `open_in_codex` can still send an artifact/tab toward an existing Mac task, but the VPS task cannot create, hand off, fork, or directly message another task.

It would be helpful to clarify whether this sensitive-tool filtering is intentional and, if so, which supported configuration or approval gate is expected to re-enable explicitly user-authorized cross-task coordination.

**Comment by dexcue** [comment]
Reproducing this on the latest macOS Codex Desktop available to me as of 2026-09-03, in a normal local Desktop task (not Remote SSH).

The important impact for my workflow is that `spawn_agent` is **not an equivalent replacement** for `create_thread`.

I intentionally use `create_thread` to create separate user-owned Desktop tasks/workers with clean, isolated context. This allows a coordinator task to delegate narrowly scoped work to several independent tasks without carrying the parent task's full orchestration/context overhead into every worker.

With the current Desktop behavior, the coordinator can no longer use the effectful thread-management surface to create those workers. Falling back to native `spawn_agent` materially changes the execution model and, in my workloads, consumes substantially more tokens because subagents participate in the multi-agent orchestration/context mechanism rather than behaving as independent Desktop tasks.

So this regression is not only a UI/task-management inconvenience; it removes a useful cost-control and context-isolation primitive.

Expected behavior:

- A root/user-owned local Codex Desktop task should be able to call `create_thread` when the user explicitly authorizes/requests creation of another Desktop task.
- `send_message_to_thread` / `handoff_thread` should likewise remain available for user-authorized inter-task coordination.
- If these tools are considered sensitive, an approval prompt or persistent opt-in is preferable to silently removing them from the callable catalog.
- Please do not treat `spawn_agent` as a functional replacement for this use case: internal subagents and independent user-owned Desktop tasks have different lifecycle, context, observability, and token-cost characteristics.

This is on macOS Codex Desktop. I can provide the exact About-dialog build/version if maintainers need it for the current release regression matrix.

**Comment by KyoungsueKim** [comment]
+ 1 same issues on Windows 11 with 26.901.51231 

-----

I’m seeing a related tool-availability problem in my current Codex desktop session, although the missing tool surface is broader than in the original report.

I asked the agent to inspect the tools actually exposed to the session. It checked both the provided tool definitions and the ALL_TOOLS catalog available through functions.exec.

These tools are all absent:
- send_message_to_thread
- create_thread
- fork_thread
- handoff_thread
- automation_update

Unlike the original report, list_threads, read_thread, and wait_threads are also absent in this session. A tool_search discovery tool is not exposed either.

The agent also checked the corresponding JavaScript properties without invoking any actions:
typeof tools.codex_app__send_message_to_thread === "undefined"

The same result was observed for create_thread, fork_thread, handoff_thread, automation_update, list_threads, read_thread, and wait_threads. There were no matching entries in ALL_TOOLS.

Meanwhile, the session’s injected desktop instructions explicitly refer to these thread-management and automation tools and tell the agent to discover and use them. This creates a mismatch between the instructions and the callable capabilities.

Environment:
- Codex desktop app (26.901.51231 )
- Bash/Linux execution environment with Windows-mounted paths visible (WSL2 2.7.11)

This confirms that the tools are unavailable to the agent in this session, but does not establish that the underlying cause is identical to this issue. I have not yet verified a before/after version comparison or reproduced it in a second fresh session.

Could this broader omission of both read and write tools be related to the same tool-catalog filtering or exposure mechanism?

**Comment by saidelike** [comment]
Still reproducing with **Codex CLI and the running App Server both at `0.153.4`** on the remote Linux host.

SSH-backed tasks retain list/read/wait and title/pin/archive helpers, but lack `create_thread`, `send_message_to_thread`, and a discovery path for their replacements. A fresh SSH-backed task shows the same omission.

On local macOS, `mcp__codex_app__create_thread` and `mcp__codex_app__send_message_to_thread` are available. I successfully used that Mac-hosted launcher to create and message a task on the **same remote Linux host**.

This suggests the missing piece is tool exposure to the SSH-hosted launcher; creating and messaging destinations on that host works through the Mac-hosted launcher.

**Comment by saidelike** [comment]
> Still reproducing with **Codex CLI and the running App Server both at `0.153.4`** on the remote Linux host.
> 
> SSH-backed tasks retain list/read/wait and title/pin/archive helpers, but lack `create_thread`, `send_message_to_thread`, and a discovery path for their replacements. A fresh SSH-backed task shows the same omission.
> 
> On local macOS, `mcp__codex_app__create_thread` and `mcp__codex_app__send_message_to_thread` are available. I successfully used that Mac-hosted launcher to create and message a task on the **same remote Linux host**.
> 
> This suggests the missing piece is tool exposure to the SSH-hosted launcher; creating and messaging destinations on that host works through the Mac-hosted launcher.

Additional finding on 0.153.4: from the remote Linux host, I connected directly to the running App Server’s Unix socket using its WebSocket protocol. thread/start and turn/start successfully created and messaged a session on that host.
The session appeared under the expected project in my local Desktop app. Follow-up messaging from the remote client worked, and I could open and continue the session directly in Desktop.
The SSH-hosted agent still lacks create_thread and send_message_to_thread. This narrows the observed failure to agent-facing tool availability; the underlying creation, messaging, and Desktop visibility path works.
One integration detail: the remote App Server returned an empty project list, while Desktop associated the new session with the correct saved project.

**Comment by saidelike** [comment]
**WORKAROUND**

Confirmed a workaround on Linux with Codex CLI/App Server 0.153.4: [codex-thread-bridge](https://github.com/saidelike/codex-thread-bridge).
It connects to the existing App Server on the same host. Tested creation, follow-up messaging, isolated Git worktrees, Desktop project visibility, and manual Desktop continuation.
After registering the MCP server on the Linux host and starting a fresh Desktop task, tell the agent:

> If native create_thread or send_message_to_thread is unavailable, discover and use the corresponding tools from codex-thread-bridge, following their declared schemas. If a native call failed with an uncertain outcome, inspect task state before retrying through the bridge.

This is an unofficial workaround; worktrees are bridge-managed, and the native tool availability issue remains.

**Comment by orosotne** [comment]
We are seeing the same missing-tool pattern in another Codex desktop session on September 14, 2026.

Environment:
- Desktop task running against a Linux project over SSH.
- `codex --version` on the remote host reports `codex-cli 0.154.0` (the desktop app build has not been verified).
- Source and destination tasks are on the same SSH host and share the project directory.

Verified in the affected session:
- `codex_app__list_threads` and `codex_app__read_thread` work; the destination task can be found and read using its `remote-ssh-discovered:…` host ID.
- `codex_app__wait_threads`, `set_thread_title`, `set_thread_archived`, and sidebar helpers are present in the tool catalog.
- `send_message_to_thread`, `create_thread`, `fork_thread`, `handoff_thread`, and `automation_update` are absent from the exposed tool catalog (`ALL_TOOLS`).
- The user explicitly asked the assistant to send an instruction to the other task, but no native send could be attempted because the tool was not exposed. This is not a failed delivery or an approval rejection.

This matches the read-tools-present / task-send-tools-missing symptom in this issue. We have not independently verified the filtering implementation or established whether SSH contributes to the problem.

Could the maintainers clarify whether this omission is intentional in Code Mode, a regression, or dependent on a feature flag/version, and whether there is a supported way to restore native cross-task messaging?

**Comment by dex-tripnull** [comment]
Corroborating cross-platform occurrence: from a Linux/WSL task launched through Windows Codex Desktop, `list_threads`, `read_thread`, and `wait_threads` were callable and resolved the intended task, but `send_message_to_thread` was absent from that task's callable tool catalog. The local Windows Desktop task could still use the native send tool to message the same remote task. This is tool exposure at the SSH-hosted source, not evidence that the destination is unreachable or that a send was rejected. No custom bridge, configuration change, or credential fallback was used. Private host, project, and task identifiers omitted.
