### ISSUE TITLE
Codex MS Store App crashes on launch (ACCESS_VIOLATION at 0x0) -- Version 26.601.2237.0

### ISSUE THREAD

**Issue by chenhaom318-prog** [openai/codex#26019]
### What version of the Codex App are you using (From “About Codex” dialog)?

26.601.2237.0 (Microsoft Store / AppX, x64)

### What subscription do you have?

ChatGPT Plus

### What platform is your computer?

Windows 10 Build 26200 (x64)

### What issue are you seeing?

The Codex desktop app never launches. Clicking the icon (Start Menu or taskbar) produces no visible window, no splash screen, no error dialog. The process starts and crashes within 1-2 seconds, leaving only Crashpad minidump files.

### What steps can reproduce the bug?

1. Install Codex from Microsoft Store (Product ID: 9PLM9XGG6VKS)
2. Click Codex icon in Start Menu
3. App process starts briefly, crashes silently
4. Crash dumps appear at: %LOCALAPPDATA%\Packages\OpenAI.Codex_2p2nqsd0c76g0\LocalCache\Roaming\Codex\web\Codex\Crashpad\reports\
5. No .codex directory is ever created
6. No window/splash/error message is ever shown

### What is the expected behavior?

Codex should launch and display either the login screen or the main application window.

### Additional information

The crash is at address 0x0000000000000000, meaning some function pointer or module reference is NULL during early initialization. This is before any user-visible code runs.

The .codex directory never gets created, confirming the crash happens before user data initialization.

This is not the codex://new deep-link protocol bug (#25297), because the crash occurs even when launching Codex.exe directly with no protocol arguments.

The app uses owl runtime (OpenAI's Electron shell), identified from resources/owl-electron-app.json: {"runtimeName":"owl","packagedFrom":"D:\\a\\openai\\openai\\codex\\codex-apps\\electron\\out\\Codex-win32-x64"}.

The AppxManifest specifies MaxVersionTested="10.0.26100.0" while the host system is running build 10.0.26200.0 (Windows Insider Dev Channel).

Codex CLI (@openai/codex v0.136.0, installed via npm) works fine on the same machine, confirming the issue is specific to the desktop app's Electron/AppX packaging, not a system-wide incompatibility.

**Comment by tbvjaosaos** [comment]
Additional reproduction on a newer Codex Desktop build.

Environment:
- Codex Microsoft Store package: `OpenAI.Codex_26.609.3341.0_x64__2p2nqsd0c76g0`
- Codex app version: `26.609.3341.0`
- Chromium runtime visible in dump strings: `149.0.7827.54`
- Windows: `Windows 10 Pro`, DisplayVersion `25H2`, build `26200`, UBR `8655`, x64
- Codex Beta package on the same machine works: `OpenAI.CodexBeta_26.527.7698.0_x64__2p2nqsd0c76g0`

Observed behavior:
- Launching from Start menu / `shell:AppsFolder\OpenAI.Codex_2p2nqsd0c76g0!App` creates the AppX process/container, then the container is destroyed ~1-3 seconds later.
- No visible UI, splash, or error dialog.
- Direct launch of `app\Codex.exe` from the package directory exits the same way.
- The normal Codex desktop log stops after:
  - `Launching app ... buildFlavor=prod ... platform=win32`
  - `Appshot hotkey inactive configured=true enabled=true platform=win32`
- It never reaches the app-server initialization lines that the Beta build reaches.

Crash artifacts:
- Crashpad minidumps are created under `%LOCALAPPDATA%\Packages\OpenAI.Codex_2p2nqsd0c76g0\LocalCache\Roaming\Codex\web\Codex\Crashpad\reports\`.
- Dump string scan shows Chromium/loader strings around:
  - `bad allocation`
  - `length_error was thrown in -fno-exceptions mode`
  - `ChromeMain`
  - `..\..\chrome\app\main_dll_loader_win.cc`
  - `Cannot find module`
  - `Failed to load Chrome DLL from`
  - `DelayLoad-ModuleName`
  - `chrome.dll`
  - `Stability.BrowserExitCodes`

Mitigations attempted without success:
- Removed/renamed the Codex package Chromium profile/cache under `%LOCALAPPDATA%\Packages\OpenAI.Codex_2p2nqsd0c76g0\LocalCache\Roaming\Codex\web`.
- `Add-AppxPackage -DisableDevelopmentMode -Register ...\AppxManifest.xml`.
- `Reset-AppxPackage -Package OpenAI.Codex_26.609.3341.0_x64__2p2nqsd0c76g0`.
- `winget repair --id 9PLM9XGG6VKS --source msstore`.
- Full uninstall/reinstall via `winget uninstall/install --id 9PLM9XGG6VKS --source msstore`.
- Direct `Codex.exe` launch with Chromium flags including `--disable-gpu`, `--disable-software-rasterizer`, `--disable-features=RendererCodeIntegrity`, `--in-process-gpu`, and `--no-pre-read-main-dll`.

This looks like the same early Chromium/AppX startup failure, still reproducible on `26.609.3341.0`. The working workaround for this machine is to use `Codex (Beta)` (`9N8CJ4W95TBZ`) until the stable Store package is fixed.

**Comment by Danrrodrigues** [comment]
Adding another data point that still reproduces on a newer Codex Desktop package.

Environment:
- Codex Desktop package: `OpenAI.Codex_26.616.4196.0_x64__2p2nqsd0c76g0`
- Codex Desktop version: `26.616.4196.0`
- Windows: `25H2`, build `26200.8655`, x64
- Global CLI: `codex-cli 0.141.0` works separately
- Package manifest still declares `MaxVersionTested="10.0.26100.0"`

Observed behavior:
- Launching from Start Menu exits before showing the UI.
- Launching by AUMID also exits: `OpenAI.Codex_2p2nqsd0c76g0!App`.
- Launching the packaged `Codex.exe` directly also exits.
- Each launch attempt creates Crashpad minidumps under the Codex Crashpad reports directory.

Troubleshooting already tried:
- `Reset-AppxPackage` for `OpenAI.Codex`
- Clean roaming profile
- Clean reinstall from Microsoft Store / winget using Store ID `9PLM9XGG6VKS`
- Chromium fallback flags: `--disable-gpu`, `--disable-gpu-compositing`, `--disable-software-rasterizer`, `--disable-features=UseSkiaRenderer,Vulkan,Dawn`, `--use-angle=warp`, `--use-gl=swiftshader`
- Compatibility layers: `WIN7RTM` and `WIN8RTM`
- Clean session without relying on the normal user environment

None of these kept the app alive on `26.616.4196.0`.

Initial minidump inspection indicated `EXCEPTION_ACCESS_VIOLATION`, with references to `chrome.dll` from the Codex package. I am not attaching dumps publicly here to avoid posting local/private data, but I can provide a Crashpad dump through a safer channel if useful.
