### ISSUE TITLE
[Windows][Codex Desktop 26.908.3777.0] Pet/avatarOverlay crashes with "r is not a function"

### ISSUE THREAD

**Issue by sayitjang** [openai/codex#44739]
### What version of the Codex App are you using (From “About Codex” dialog)?

26.908.3777.0

### What subscription do you have?

ChatGPT Plus

### What platform is your computer?

Windows 11 Professional, 64-bit Build 22621

### What issue are you seeing?

The Codex Pet/avatar overlay crashes immediately after enabling “Show Pet”.

When I click “Show Pet”, the Pet appears briefly for about 1 second, then the Pet overlay switches to the generic “ChatGPT has encountered a problem” error screen.

The normal Codex/ChatGPT conversation UI continues to work correctly. The issue appears to be isolated to the Pet/avatarOverlay renderer.

The desktop log consistently shows the following React error:

errorMessage="r is not a function"
errorName=Error
errorStack="Error: r is not a function"
name=AppRoutes
rendererWindowAppearance=avatarOverlay
rendererWindowVisible=true

The avatarOverlay window itself appears to initialize successfully before the React error occurs.

<img width="683" height="490" alt="Image" src="https://github.com/user-attachments/assets/ef46cbb8-1759-456e-93d5-71f20c3afb19" />

### What steps can reproduce the bug?

1. Launch the Codex/ChatGPT desktop app on Windows.
2. Open the Pet settings.
3. Click “Show Pet”.
4. The Pet appears briefly for approximately 1 second.
5. The Pet overlay immediately changes to the “ChatGPT has encountered a problem” error screen.

The issue reproduces consistently in my environment.

### What is the expected behavior?

The Pet should remain visible and functional after clicking “Show Pet”, without the avatarOverlay renderer entering an error boundary.

### Additional information

The issue appears to be specific to the Pet/avatarOverlay React renderer.

Relevant log entries:

[window-manager] window main frame finished load appearance=avatarOverlay
[window-manager] window ready-to-show appearance=avatarOverlay

Shortly afterward:

error [electron-message-handler] error boundary
errorMessage="r is not a function"
errorName=Error
errorStack="Error: r is not a function"
name=AppRoutes
rendererWindowAppearance=avatarOverlay
rendererWindowVisible=true

Troubleshooting already attempted:

- Reset the Windows app through Windows Settings.
- Restarted the app multiple times.
- Tested Windows display scaling at both 125% and 100%.
- The issue occurs at both scaling values.
- Normal Codex conversations work correctly.
- Codex doctor reports 0 failures.
- Reproduced the issue multiple times with the same avatarOverlay React error.
- Temporarily tested plugin/config-related troubleshooting, but the Pet crash remained reproducible.
- Restored the original configuration afterward.

Feedback was also submitted through the in-app /feedback command.

Feedback ID:
no-active-thread-01a08f17-293e-73e3-8326-9a84c949ef39

Reproduction frequency: 100% in my environment.

**Comment by sayitjang** [comment]
Thanks for identifying the potential duplicates.

I reviewed the suggested issues. #44687 appears potentially related because it reports the same frontend exception:

`Error: r is not a function`
`name=AppRoutes`

However, my reproduction is specifically on Windows and is isolated to the Pet/avatarOverlay renderer:

- Windows 11 x64
- Codex Desktop 26.908.3777.0
- Normal Codex/chat UI works correctly
- Clicking "Show Pet" reproduces the failure 100% of the time
- The Pet appears briefly, then the avatar overlay enters the error boundary
- The log specifically shows:
  `rendererWindowAppearance=avatarOverlay`
  `rendererWindowVisible=true`
  `errorMessage="r is not a function"`

#44687 appears to involve macOS and route prefetch/AppRoutes rather than the Pet/avatarOverlay path.

#44720 appears to share the generic "ChatGPT hit a snag" symptom, but I have a deterministic Pet-specific reproduction and a different failure signature.

#44738 appears related to bundled marketplace/startup behavior on macOS. I tested plugin-related troubleshooting locally, but the Pet crash remained reproducible with the same AppRoutes error.

I am leaving this issue open for now because it provides a deterministic Windows-specific avatarOverlay reproduction. If maintainers confirm that #44687 has the same root cause, please feel free to close this as a duplicate.

Feedback ID:
`no-active-thread-01a08f17-293e-73e3-8326-9a84c949ef39`

**Comment by hr168** [comment]
提示词：禁止自动更新codex app，禁止windows store ，app store 自动更新codex app

**Comment by sebscrim** [comment]
I can reproduce the same Pet/avatarOverlay failure on macOS, with the same renderer exception.

Environment:
- macOS 26.6.2
- Apple Silicon / arm64
- ChatGPT/Codex 26.908.31748 (build 8720)
- Codex app-server 0.154.0-alpha.6.1
- ChatGPT Plus

Behavior:
- Main ChatGPT/Codex window continues working normally.
- Showing the built-in Pet opens the avatar overlay.
- The overlay displays "ChatGPT hit a snag."
- The main application and local app-server remain functional.

Launching the app from Terminal produces the same error signature:

```text
TypeError: r is not a function

errorMessage="r is not a function"
errorName=Error
name=AppRoutes
rendererWebContentsId=2
rendererWindowAppearance=avatarOverlay
rendererWindowVisible=true

**Comment by 7015015-cmyk** [comment]
Update: the issue is still reproducible after updating Codex Desktop on Windows 11 to version `26.908.4561.0`.

Behavior is unchanged:
- Main Codex/chat UI works normally.
- Enabling **Show Pet** briefly shows the Pet, then the `avatarOverlay` renderer crashes.
- The overlay shows the generic error screen.
- The failure remains isolated to the Pet/avatarOverlay path.

So this is **not fixed in 26.908.4561.0** on my Windows 11 system.

**Comment by sergeygordon-badbot** [comment]
В Windows-версии 26.908.4561.0 питомец не загружается. Журнал показывает ошибку `r is not a function` в окне питомца. Основной чат работает. Просьба исправить.

**Comment by GigaBonde** [comment]
Same avatarOverlay failure on **26.908.40401** (Store package `OpenAI.Codex` 26.908.4561.0), Windows 11 Pro 25H2 build 26200, Electron 42.3.0, codex-cli 0.154.0-alpha.6.2. First seen on the first launch after the update from 26.904/26.905 (2026-09-11T18:24Z); zero occurrences on the earlier builds. #44720 was closed as completed, but 26.908.4561.0 still ships the cycle.

Both halves of the cycle are visible in this build's `app.asar`:

```js
// authed-route-bccf47ed0783.js
import{Dc as t,Oc as n,kc as r}from"./app-primary-c24bccad67ce.js";
var o,s=e((()=>{a(),o=i({name:`smartphone-light-16`,...})}));
r();   // column 1573: kc from app-primary, called at module evaluation
export{t as AppLayoutRoute,n as AuthedRoute,o as n,s as t};

// app-primary-c24bccad67ce.js
import{n as aZe,t as oZe}from"./authed-route-bccf47ed0783.js"
... HMt as kc ...
```

Two things to add to the Pet report:

1. **It also kills voice chat**, which runs in the same avatarOverlay window. The overlay is created at every launch and hits the error boundary 4 to 19 s after `ready-to-show` (6 of 6 launches on 2026-09-12). Voice never reaches `Starting realtime voice transport`; the only line is `[avatar-overlay-realtime] Voice chat took too long to start cancellationOrigin=host_timeout` after ~30 s, with the microphone never opened. 9 of 9 attempts today. On 26.905 the same click logged `Starting realtime voice transport → realtime_session_started → realtime_session_updated realtimeSessionId=rtc_...`.
2. Confirming that clearing caches is not a fix: moving the Chromium caches and the bundled marketplace caches (#44738) gives one clean launch of the primary window, then it recurs; the overlay crashes regardless.

In-app **Send feedback fails** on this build too (`feedback/upload` → Sentry envelope: `An existing connection was forcibly closed by the remote host. (os error 10054)`), so this cannot be reported from inside the app.

**Comment by GigaBonde** [comment]
Follow-up: the Store has since delivered **26.908.4834.0** (bundle `26.908.40834`), and it fixes this. In that package `authed-route-*.js` is 116 bytes and only imports from `app-primary-*.js`; `app-primary` no longer imports the route module, so the cycle is gone. First launch: 0 `Initial route prefetch failed`, 0 error boundaries, the avatar overlay opens without crashing, and voice chat starts normally (`Starting realtime voice transport` → `realtime_session_started`).

One thing worth knowing for anyone still on 26.908.4561.0: the app's own update check is gated behind a UI policy latch (`in_app_updates_policy_latch ... policy=pending` → `policy=allowed` → `[windows-store-updater] Checking Windows Store for package updates`). With the primary window crashed, the latch never reaches `allowed`, so the app never asks the Store and "Update ChatGPT" reports "up to date". On this machine that meant a full day with 0 update checks. Opening Microsoft Store → Library → Check for updates pulled the fixed package immediately.

**Comment by 7015015-cmyk** [comment]
Confirmed fixed on Windows in Codex Desktop 26.908.4834.0. Pet/avatarOverlay now works normally for me.
